/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import io.EMnistDataReader;
import io.ImageLoader;
import io.*;
import network.Network;
import network.grid.DenseGrid;
import network.layer.*;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

/**
 * @author Luecx
 */
public class EMNISTFrame extends javax.swing.JFrame {

    private javax.swing.JProgressBar[] progressBars = new javax.swing.JProgressBar[62];
    private Network network;
    /**
     * Creates new form NewJFrame
     */
    public EMNISTFrame(Network network) {
        initComponents();

        this.network = network;


        this.addMouseListener(jPanel4);
        this.addMouseMotionListener(jPanel4);

        double[] randomInitValuesForTom = new double[62];
        for(int i = 0; i < randomInitValuesForTom.length; i++){
            randomInitValuesForTom[i] = Math.random();
        }
        this.updateOutputs(randomInitValuesForTom);

        jButton1ActionPerformed(null);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Network net = Network.loadNetwork("res/networks/ADAM.bin");

//                new EMNISTFrame(net).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {


        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new DrawPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        outputDigit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        for(int i=0;i<progressBars.length;i++){
            progressBars[i] = new javax.swing.JProgressBar();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1500, 1000));
        setResizable(false);
        getContentPane().setLayout(new GridLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("InputImage"));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jPanel4.setMaximumSize(new Dimension(468, 468));
        jPanel4.setMinimumSize(new Dimension(468, 468));
        jPanel4.setPreferredSize(new Dimension(468, 468));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 462, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new GridLayout());

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setText("Go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Computed"));

        outputDigit.setFont(new Font("Sans serif", 0, 400)); // NOI18N
        outputDigit.setText(" ");
        jPanel2.add(outputDigit);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Network outputs"));

        GridLayout experimentLayout = new GridLayout(62,2);
        jPanel1.setLayout(experimentLayout);
        for(int i =0;i<62;i++){
            JLabel l = new JLabel(Classes.values()[i].name());
            l.setForeground(Color.blue);
            l.setPreferredSize(new Dimension(50,10));
            jPanel1.add(l);
                jPanel1.add(progressBars[i]);
        }

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>                        



    void updateOutputs(double[] output) {
        for (int i = 0; i < output.length; i++) {
            progressBars[i].setMinimum(0);
            progressBars[i].setMaximum(1000);
            progressBars[i].setStringPainted(true);

            progressBars[i].setValue((int) (output[i] * 1000));
            progressBars[i].setString((int) (output[i] * 1000)/10d+"%");
        }

        this.revalidate();
        this.repaint();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Graphics g = jPanel4.getBufferedImage().getGraphics();
        g.setColor(Color.BLACK);
        g.fillRect(0,0,1000,1000);
        jPanel4.repaint();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        BufferedImage img = jPanel4.getBufferedImage();
        BufferedImage scaled = ImageLoader.getScaledImage(img, 128,128);

        DenseGrid o = new DenseGrid(128,128,1);

        for(int i = 0; i < 128; i++){
            for(int n = 0; n < 128; n++){
                Color c = new Color(scaled.getRGB(i,n));
                float v = c.getRed() / 255f;
                o.set(i,n,0,v);
            }
        }
        DenseGrid out = (DenseGrid) network.compute(o);



//        ImageLoader.displayImage(ImageLoader.tensorToImage(network.getInputLayer().getOutput(), ImageLoader.NORMALISE));

        updateOutputs(out.raw());
        outputDigit.setText("" + Classes.values()[out.indexOfMax()].getMeaning());
    }



    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EMNISTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//
//                Network net = Network.loadNetwork("res/ADAM.bin");
//
//                new EMNISTFrame(net).setVisible(true);
//            }
//        });
//    }

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private DrawPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel outputDigit;
}
